bot/urls.py
from django.urls import path
from bot import views

urlpatterns = [
    path('bot/', views.bot, name="bots"),
    path('list/bot/', views.listBot, name="listBot")
]

uploadmeapp/urls.py
from django.contrib import admin
from django.urls import path, include
from os import getenv
from django.conf import settings #for media if debug is true in localhost
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('files.urls')),
    path('', include('users.urls')),
    path('', include('bot.urls')),
]

#CREADOTEO for media
if settings.DEBUG and str(getenv('USE_S3_CLOUD')) != '1':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path,include
from users import views
from django.contrib.auth import views as auth_views #import this

urlpatterns = [
    path('robots.txt/', views.get_robot_file,name="robots"),
    path('signup/', views.signupUser, name="signup"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logout_request, name= "logout"),
    path('profile/edit/',views.profile_edit, name="profile_add"),

    path("password_reset/", auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html"), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

User._meta.get_field('email').blank = False
User._meta.get_field('email').null = False

# Create your models here.
class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=100,verbose_name='Teléfono:',blank=True,null=True)
    address = models.CharField(max_length=100, verbose_name='Dirección:', help_text='Ingrese la dirección',blank=True,null=True)

    class Meta:
        unique_together = ('phone_number',)

users/forms.py
from django import forms
from django.db import models
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from .models import Person

# Create your forms here.
#CREADOTEO
class CustomNewUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username","email", "password1", "password2")

    # def save(self, commit=True):
    #     user = super(CustomNewUserForm, self).save(commit=False)
    #     user.email = self.cleaned_data['email']
    #     if commit:
    #         user.save()
    #     return user


class ProfileForm(UserChangeForm):
    password = None
    #overwrite
    class Meta:
        model = User
        fields = ('first_name','last_name','email')
        labels = {
            "first_name": _("Nombre:"),
            "last_name": _("Apellidos:"),
            "email": _("Email:")
        }

class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ('phone_number','address')
        unique_together = ('phone_number',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['phone_number'].widget.attrs.update({'id': 'phone'})

users/views.py
from ast import Not
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout, models #CREADOTEO
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ObjectDoesNotExist

from users.forms import CustomNewUserForm, ProfileForm, PersonForm
# Create your views here.

def signupUser(request):
    if request.user.is_authenticated:
        return redirect("/")
    context = {}
    if request.method == "POST":
        form = CustomNewUserForm(request.POST)
        form_person = PersonForm(request.POST)
        if form.is_valid() and form_person.is_valid():
            user = form.save()
            form_person = form_person.save(commit=False)
            form_person.user = user
            form_person.save()
            login(request, user)
            messages.success(request, f"Te has registrado correctamente {user.username}")
            return redirect("/")
    else:
        form = CustomNewUserForm()
        form_person = PersonForm()
    context={
        'form': form,
        'form_person':form_person
    }
    return render(request, "registration/signup.html", context)

def get_robot_file(request):
    return render(request, 'robots.txt',content_type='text/plain')

def loginUser(request):
    if request.user.is_authenticated:
        return redirect("/")
    context = {}
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"Has iniciado sesión {username}.")
                return redirect("/")
    else:
        form = AuthenticationForm()
    context={
        "login_form": form
    }
    return render(request, template_name="registration/login.html", context=context)

def logout_request(request):
    logout(request)
    messages.success(request, f"Has cerrado sesión con éxito")
    return render(request, 'home.html')

def profile_edit(request):
    context={}
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=request.user)
        try:
            form_person = PersonForm(request.POST, instance=request.user.person)
        except ObjectDoesNotExist:
            form_person = PersonForm(request.POST)

        if form.is_valid() and form_person.is_valid():
            user = form.save()
            form_person = form_person.save(commit=False)
            form_person.user = user
            form_person.save()
            messages.success(request, "Información actualizada correctamente")
            return redirect(profile_edit)
    else:
        form = ProfileForm(instance=request.user)
        try:
            form_person = PersonForm(instance=request.user.person)
        except ObjectDoesNotExist:
            form_person = PersonForm()
    context={
        'form': form,
        'form_person': form_person,
        'username': request.user.username
    }
    return render(request, "profile/profile.html", context)

users/templates/profile/profile.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block titulo %} Subeme-logIn {% endblock %}

{% block head %}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/css/intlTelInput.css"/>
{% endblock %}

{% block style %}
    <style>
        .login-style{
            width: 800px;
            margin: auto;
        }
        .iti {
			width: 100%;
		}
    </style>

{% endblock %}

{% block content %}

<div class="container py-5 login-style">
    <h1>Perfil</h1>

    <form method="POST" action="{% url 'profile_add' %}" id="idProfileForm" novalidate>
        {% csrf_token %}
        <div class="mb-3">
            <label for="usernameinput" class="form-label">Nombre de usuario:</label>
            <input type="text" class="form-control" id="usernameinput" value="{{username}}" aria-describedby="usernameHelp" disabled>
            <div id="usernameHelp" class="form-text">Este usuario no se puede cambiar una vez creado</div>
        </div>
        {{form |crispy}}
        {{form_person |crispy}}
        <button type="submit" class="btn btn-sm btn-primary">Guardar</button>
    </form>
</div>

{% endblock %}

{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>
    <script type="text/javascript">
        const phoneInputField = document.querySelector("#phone");
        const phoneInput = window.intlTelInput(phoneInputField, {
        preferredCountries: ["co", "us", "es", "mx"],
        utilsScript:
            "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/utils.js",
        });
    </script>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            nameInputDefault = jQuery("#id_first_name").val();
            lastNameInputDefault = jQuery("#id_last_name").val();
            emailInputDefault = jQuery("#id_email").val();
            phoneNumber = jQuery("#phone").val();
            address = jQuery("#id_address").val();
            
            jQuery("#idProfileForm").submit(function(event){
                if (jQuery("#id_first_name").val() === nameInputDefault && jQuery("#id_last_name").val() === lastNameInputDefault && jQuery("#id_email").val() === emailInputDefault && phoneInput.getNumber() === phoneNumber && jQuery("#id_address").val() === address){
                    alert("No guardaste nada");
                    event.preventDefault();
                    return;
                }
                jQuery("#phone").val(phoneInput.getNumber());
            });

        });
    </script>
{% endblock %}